version: "3.8"
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "1815:1815"
    env_file:
      - .env
    environment:
      - GIN_MODE=release
    volumes:
      - ./logs:/app/logs
