version: "3.8"
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "1815:1815"
    environment:
      - GIN_MODE=release
      - DB_HOST=82.112.230.106
      - DB_USERNAME=anierp
      - DB_PASSWORD=secret
      - DB_DATABASE=nitik_batik
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
